import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright-core';
import { resolveChrome } from '../lib/config.mjs';

const baseUrl = process.env.SCREENREEL_EXAMPLE_URL || 'http://127.0.0.1:4173/examples/action-showcase/';
const output = path.resolve('./screenreel-output/browser-smoke'); fs.mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ executablePath: resolveChrome(), args: ['--hide-scrollbars'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
async function visiblePill(targetPage) {
  const pill = targetPage.locator('.sr-pill');
  await pill.waitFor();
  const handle = await pill.elementHandle();
  await targetPage.waitForFunction((element) => getComputedStyle(element).position === 'absolute', handle);
  return pill;
}
try {
  page.on('console', (message) => { if (message.type() === 'error') console.error('[browser]', message.text()); });
  page.on('pageerror', (error) => console.error('[pageerror]', error.message));
  page.on('response', (response) => { if (response.status() >= 400) console.error('[response]', response.status(), response.url()); });
  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear(); }); await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => !!customElements.get('screenreel-projector'));
  const trigger = page.locator('screenreel-projector').locator('button[aria-label="Toggle ScreenReel demo"]'); await trigger.waitFor(); assert.equal(await trigger.count(), 1); await trigger.click();
  const pill = await visiblePill(page); assert.equal(await pill.count(), 1);
  await page.locator('button[title="Presenter notes"]').click(); assert.match(await page.locator('body').evaluate((node) => node.style.paddingBottom), /clamp/);
  await page.screenshot({ path: path.join(output, 'projector-1280x720.png') });
  await page.locator('button[title="Presenter notes"]').click();
  await page.locator('button[title="Play"]').click();
  await page.locator('.sr-action-box,.sr-glow-box').waitFor({ state: 'visible', timeout: 5000 });
  await page.waitForFunction(() => document.querySelector('#customer-name')?.value === 'Northstar Retail' && document.querySelector('#region')?.value === 'West' && document.querySelector('#priority')?.checked && document.querySelector('#confidence')?.value === '82', null, { timeout: 20000 });
  assert((await page.evaluate(() => window.scrollY)) > 0);
  await page.waitForFunction(() => document.querySelector('#activity-scroll')?.scrollTop > 20, null, { timeout: 10000 });
  await page.waitForFunction(() => document.querySelector('#delayed-target')?.hidden === false && document.querySelector('#hero-result')?.textContent === 'Safe page function called', null, { timeout: 10000 });
  await page.waitForURL(/destination\.html\?from=showcase/, { waitUntil: 'domcontentloaded', timeout: 15000 });
  await visiblePill(page); await page.locator('.sr-glow-box').waitFor({ state: 'visible', timeout: 5000 });
  assert.equal(await page.locator('.sr-count').innerText(), '5/5');
  await page.locator('button[title="Pause"]').click();
  await page.screenshot({ path: path.join(output, 'projector-destination-1280x720.png') });
  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' }); await visiblePill(page);
  await page.locator('button[title="Open ScreenReel Studio"]').click(); const heading = page.getByRole('heading', { name: 'Demo flows', exact: true }); await heading.waitFor();
  const duplicate = page.getByRole('button', { name: 'Duplicate', exact: true }); assert.equal(await duplicate.count(), 1); await duplicate.click();
  const localCard = page.locator('.sr-flow-card').filter({ hasText: 'All actions showcase copy' }); assert.equal(await localCard.count(), 1); await localCard.getByRole('button', { name: 'Open', exact: true }).click();
  await page.getByRole('heading', { name: 'All actions showcase copy', exact: true }).waitFor(); assert.equal(await page.locator('.sr-scene-table tbody tr').count(), 5);
  const editButtons = page.getByRole('button', { name: 'Edit', exact: true }); assert.equal(await editButtons.count(), 5); await editButtons.nth(0).click();
  const titleField = page.locator('[data-field="title"]'); await titleField.fill('Studio-authored highlight');
  await page.getByRole('button', { name: 'Add action', exact: true }).click(); assert.equal(await page.locator('[data-definition]').count(), 20); assert.equal(await page.locator('[data-recipe]').count(), 6);
  await page.locator('[data-definition="highlight"]').click(); const preview = page.frameLocator('.sr-preview-frame'); const kpiValue = preview.locator('[data-kpi="revenue"] strong'); await kpiValue.click();
  const savedTarget = page.locator('.sr-action small').filter({ hasText: '[data-kpi="revenue"]' }); await savedTarget.waitFor(); assert.equal(await savedTarget.count(), 1);
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  assert.equal(await page.locator('.sr-dirty').count(), 0);
  assert(await page.evaluate(() => JSON.parse(localStorage.getItem('screenreel:action-showcase:flows:v1')).flows.some((flow) => flow.scenes.some((scene) => scene.title === 'Studio-authored highlight' && scene.actions.length === 6))));
  await page.getByRole('button', { name: 'Back to scenes', exact: true }).click();
  await page.getByRole('heading', { name: 'All actions showcase copy', exact: true }).waitFor(); assert.equal(await page.locator('.sr-scene-table tbody tr').filter({ hasText: 'Studio-authored highlight' }).count(), 1);
  await page.setViewportSize({ width: 1440, height: 900 }); await page.screenshot({ path: path.join(output, 'studio-1440x900.png') });
  await page.getByRole('button', { name: 'Play flow', exact: true }).click();
  await page.locator('.sr-studio').waitFor({ state: 'detached' });
  await page.locator('.sr-action-box,.sr-glow-box').waitFor({ state: 'visible', timeout: 5000 });
  assert.equal(await page.locator('.sr-flow').evaluate((node) => node.selectedOptions[0].textContent), 'All actions showcase copy');
  await page.locator('button[title="Pause"]').click();
  const spaPage = await browser.newPage({ viewport: { width: 1280, height: 720 } }); await spaPage.goto(new URL('../spa-router/', baseUrl).href, { waitUntil: 'domcontentloaded' });
  const spaTrigger = spaPage.locator('#demo-button'); await spaTrigger.waitFor(); await spaTrigger.click(); await visiblePill(spaPage);
  await spaPage.locator('button[title="Play"]').click(); await spaPage.locator('.sr-glow-box').waitFor({ state: 'visible', timeout: 5000 });
  await spaPage.locator('button[title="Next scene"]').click(); await spaPage.waitForURL(/view=details/); await spaPage.locator('.sr-action-callout').waitFor({ state: 'visible', timeout: 5000 });
  assert.match(spaPage.url(), /view=details/); await spaPage.locator('button[title="Pause"]').click(); await spaPage.close();
  const inlinePage = await browser.newPage({ viewport: { width: 1280, height: 720 } }); await inlinePage.goto(new URL('../inline-flow/', baseUrl).href, { waitUntil: 'domcontentloaded' }); const inlineTrigger = inlinePage.locator('#demo-button'); await inlineTrigger.waitFor(); await inlineTrigger.click(); const inlinePill = await visiblePill(inlinePage); assert.equal(await inlinePill.count(), 1); await inlinePage.close();
  const darkContext = await browser.newContext({ colorScheme: 'dark', viewport: { width: 1440, height: 900 } }); const darkPage = await darkContext.newPage(); await darkPage.goto(baseUrl, { waitUntil: 'domcontentloaded' }); const darkTrigger = darkPage.locator('screenreel-projector').locator('button[aria-label="Toggle ScreenReel demo"]'); await darkTrigger.waitFor(); await darkTrigger.click(); await visiblePill(darkPage); await darkPage.waitForFunction(() => getComputedStyle(document.documentElement).backgroundColor === 'rgb(9, 9, 11)'); await darkPage.screenshot({ path: path.join(output, 'projector-dark-1440x900.png') }); await darkContext.close();
  console.log(JSON.stringify({ ok: true, screenshots: fs.readdirSync(output).map((name) => path.join(output, name)) }, null, 2));
} finally { await browser.close(); }
