import fs from 'fs';
import path from 'path';
import '../packages/core/action-runtime.js';

const root = path.resolve(new URL('..', import.meta.url).pathname); const out = path.join(root, 'dist/projector');
fs.rmSync(path.join(root, 'dist'), { recursive: true, force: true }); fs.mkdirSync(out, { recursive: true });
for (const [source, target] of [
  ['packages/projector/screenreel.js', 'screenreel.js'], ['packages/projector/projector.js', 'projector.js'], ['packages/projector/icons.js', 'icons.js'], ['packages/projector/screenreel.css', 'screenreel.css'],
  ['packages/studio/studio.js', 'studio.js'], ['packages/core/action-runtime.js', 'action-runtime.js'], ['packages/core/flow-store.js', 'flow-store.js'],
]) fs.copyFileSync(path.join(root, source), path.join(out, target));

const definitions = globalThis.ScreenReelCore.definitions;
const actionTypes = [...new Set(definitions.map((item) => item.type).concat(['fill']))];
const schema = { $schema: 'https://json-schema.org/draft/2020-12/schema', title: 'ScreenReel Manifest', type: 'object', required: ['schemaVersion', 'flows'], properties: { schemaVersion: { const: 1 }, flows: { type: 'array', items: { $ref: '#/$defs/flow' } } }, $defs: { flow: { type: 'object', required: ['id', 'name', 'scenes'], properties: { id: { type: 'string' }, name: { type: 'string' }, defaults: { type: 'object' }, scenes: { type: 'array', items: { $ref: '#/$defs/scene' } } }, additionalProperties: true }, scene: { type: 'object', required: ['id', 'route', 'actions'], properties: { id: { type: 'string' }, enabled: { type: 'boolean' }, route: { type: 'string' }, title: { type: 'string' }, talkingPoints: { type: 'string' }, waitFor: { type: 'string' }, timeoutMs: { type: 'number', minimum: 100 }, settleMs: { type: 'number', minimum: 0 }, dwellMs: { type: 'number' }, actions: { type: 'array', items: { $ref: '#/$defs/action' } } }, additionalProperties: true }, action: { type: 'object', required: ['type'], properties: { id: { type: 'string' }, type: { enum: actionTypes }, selector: { type: 'string' }, afterMs: { type: 'number' } }, additionalProperties: true } } };
fs.writeFileSync(path.join(out, 'screenreel.schema.json'), `${JSON.stringify(schema, null, 2)}\n`);
fs.writeFileSync(path.join(out, 'screenreel.d.ts'), `export interface ScreenReelManifest { schemaVersion: 1; flows: ScreenReelFlow[] }\nexport interface ScreenReelFlow { id: string; name: string; defaults?: Record<string, unknown>; scenes: ScreenReelScene[] }\nexport interface ScreenReelScene { id: string; enabled?: boolean; route: string; title?: string; talkingPoints?: string; waitFor?: string; timeoutMs?: number; settleMs?: number; dwellMs?: number; leadInMs?: number; tailMs?: number; endsInNavigation?: boolean; actions: ScreenReelAction[] }\nexport interface ScreenReelAction { id?: string; type: ${actionTypes.map((type) => `'${type}'`).join(' | ')}; selector?: string; index?: number; afterMs?: number; [key: string]: unknown }\nexport interface ScreenReelRouter { getRoute(): string; navigate(route: string): void | Promise<void>; subscribe?(listener: () => void): () => void }\nexport interface ScreenReelLegacyStorage { id?: string; flowsKey?: string; activeFlowKey?: string; notesVisibleKey?: string; enabledKey?: string; session?: { positionKey?: string; playingKey?: string; navigationKey?: string } }\nexport interface ScreenReelValidationAction { actionIndex: number; actionId?: string; type: string; selector?: string; errors: string[] }\nexport interface ScreenReelValidationReport { ok: boolean; flowId: string; sceneId: string | null; route: string | null; sceneErrors: string[]; actions: ScreenReelValidationAction[] }\nexport interface ScreenReelOptions { projectId: string; flow: { src: string } | { data: ScreenReelManifest }; assetBase?: string; activationQueryParam?: string; notesMode?: 'reserve' | 'overlay'; loop?: boolean; strict?: boolean; routesEqual?: (currentRoute: string, sceneRoute: string) => boolean; router?: ScreenReelRouter; legacyStorage?: ScreenReelLegacyStorage }\nexport interface ScreenReelProjector { enable(): this; disable(): this; play(): Promise<void>; pause(): this; validateScene(sceneId?: string): ScreenReelValidationReport; openStudio(options?: Record<string, unknown>): Promise<unknown>; destroy(): void }\nexport interface ScreenReelApi { mount(target: Element, options: ScreenReelOptions): Promise<ScreenReelProjector>; openStudio(options?: Record<string, unknown>): Promise<unknown>; registerFn(name: string, fn: (...args: unknown[]) => unknown): () => void; unregisterFn(name: string, fn?: (...args: unknown[]) => unknown): void; validateScene(sceneId?: string): ScreenReelValidationReport }\ndeclare global { interface Window { ScreenReel: ScreenReelApi & { ready: Promise<ScreenReelApi> } } }\n`);
const actionReference = ['# ScreenReel actions', '', 'Generated from `packages/core/action-runtime.js`.', '', '| Action | Type | Category | Picker | Defaults |', '|---|---|---|---|---|', ...definitions.map((item) => `| ${item.label} | \`${item.type}\` | ${item.category} | ${item.picker} | \`${JSON.stringify(item.defaults)}\` |`), '', '## Recipes', '', ...globalThis.ScreenReelCore.recipes.map((item) => `- **${item.label}** (\`${item.id}\`): expands into editable primitive actions.`), ''].join('\n');
for (const directory of ['skills/screenreel/references', 'skills/screenreel-projector/references', 'skills/screenreel-capture/references']) fs.writeFileSync(path.join(root, directory, 'actions.md'), actionReference);
console.log(`Built ${fs.readdirSync(out).length} browser assets in ${out}`);
