let activeStudio;
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const clone = (value) => JSON.parse(JSON.stringify(value));

class Studio {
  constructor(options) { this.projector = options.projector; this.store = options.store; this.assetBase = options.assetBase; this.flowId = options.flowId; this.sceneId = options.sceneId; this.view = this.flowId ? (this.sceneId ? 'editor' : 'scenes') : 'flows'; this.dirty = false; this.failedAction = -1; }
  open() {
    this.host = document.createElement('div'); document.body.appendChild(this.host); this.shadow = this.host.attachShadow({ mode: 'open' }); const link = document.createElement('link'); link.rel = 'stylesheet'; link.href = new URL('screenreel.css', this.assetBase).href; this.shadow.appendChild(link);
    this.shell = document.createElement('div'); this.shell.className = 'sr-studio'; this.shadow.appendChild(this.shell); this.beforeUnload = (event) => { if (this.dirty) { event.preventDefault(); event.returnValue = ''; } }; addEventListener('beforeunload', this.beforeUnload); this.loadDraft(); this.render(); return this;
  }
  loadDraft() { const flow = this.store.getFlow(this.flowId) || this.store.activeFlow(); this.flowId = flow?.id; this.draft = flow ? clone(flow) : null; if (this.sceneId && !this.draft?.scenes.some((scene) => scene.id === this.sceneId)) this.sceneId = null; }
  close() { if (this.dirty && !confirm('Discard unsaved ScreenReel changes?')) return; this.cancelPicker(); removeEventListener('beforeunload', this.beforeUnload); this.host.remove(); activeStudio = null; }
  head() { return `<header class="sr-studio-head"><div class="sr-studio-brand"><span>Screen</span>Reel Studio</div>${this.dirty ? '<span class="sr-dirty">Unsaved changes</span>' : ''}<button data-global="ai">Copy AI context</button><button data-global="close" aria-label="Close Studio">Close</button></header>`; }
  render() { this.cancelPicker(); this.shell.innerHTML = this.head() + '<main class="sr-studio-body"></main>'; this.body = this.shell.querySelector('.sr-studio-body'); if (this.view === 'flows') this.renderFlows(); else if (this.view === 'scenes') this.renderScenes(); else this.renderEditor(); this.shell.querySelector('[data-global="close"]').onclick = () => this.close(); this.shell.querySelector('[data-global="ai"]').onclick = () => this.copyAiContext(); }
  toast(message) { this.shadow.querySelector('.sr-toast-studio')?.remove(); const node = document.createElement('div'); node.className = 'sr-toast-studio'; node.textContent = message; this.shell.appendChild(node); setTimeout(() => node.remove(), 2400); }
  renderFlows() {
    const flows = this.store.allFlows(); this.body.innerHTML = `<section class="sr-page"><div class="sr-page-title"><div><h1>Demo flows</h1><p>Canonical flows stay read-only. Personal changes remain in this browser.</p></div><div class="sr-toolbar"><button data-new>New flow</button><button data-import>Import JSON</button><button data-clear class="sr-danger">Clear local data</button></div></div><div class="sr-flow-grid">${flows.map((flow) => `<article class="sr-flow-card"><div><h3>${esc(flow.name)}</h3><div class="sr-flow-meta">${flow.scenes.length} scenes · ${flow.readonly ? 'Canonical' : 'Local'}</div></div><div class="sr-flow-actions"><button class="sr-primary" data-open="${esc(flow.id)}">Open</button><button data-duplicate="${esc(flow.id)}">Duplicate</button>${flow.readonly ? '' : `<button data-rename="${esc(flow.id)}">Rename</button><button class="sr-danger" data-delete="${esc(flow.id)}">Delete</button>`}</div></article>`).join('')}</div></section>`;
    this.body.querySelectorAll('[data-open]').forEach((button) => button.onclick = () => { this.flowId = button.dataset.open; this.view = 'scenes'; this.loadDraft(); this.render(); });
    this.body.querySelectorAll('[data-duplicate]').forEach((button) => button.onclick = () => { const flow = this.store.createCopy(this.store.getFlow(button.dataset.duplicate)); this.store.save(flow); this.render(); });
    this.body.querySelectorAll('[data-rename]').forEach((button) => button.onclick = () => { const flow = this.store.getFlow(button.dataset.rename); const name = prompt('Flow name', flow.name); if (name?.trim()) { flow.name = name.trim(); this.store.save(flow); this.render(); } });
    this.body.querySelectorAll('[data-delete]').forEach((button) => button.onclick = () => { if (confirm('Delete this local flow?')) { this.store.delete(button.dataset.delete); this.render(); } });
    this.body.querySelector('[data-new]').onclick = () => { const flow = this.store.createBlank(prompt('Flow name') || 'New demo flow'); this.store.save(flow); this.render(); };
    this.body.querySelector('[data-import]').onclick = () => this.importFile(); this.body.querySelector('[data-clear]').onclick = () => { if (confirm('Clear only ScreenReel data for this project?')) { this.store.clearAll(); this.store.ready().then(() => { this.flowId = null; this.render(); }); } };
  }
  ensureEditable() { if (!this.draft.readonly) return; const sceneIndex = this.draft.scenes.findIndex((scene) => scene.id === this.sceneId); this.draft = this.store.createCopy(this.draft, `My ${this.draft.name}`); this.flowId = this.draft.id; if (sceneIndex >= 0) this.sceneId = this.draft.scenes[sceneIndex].id; this.dirty = true; this.toast('Created a local copy'); }
  renderScenes() {
    if (!this.draft) return this.backToFlows();
    this.body.innerHTML = `<section class="sr-page"><div class="sr-page-title"><div><h1>${esc(this.draft.name)}</h1><p>Reorder, enable, or edit the scenes in this flow.</p></div></div><div class="sr-toolbar"><button data-back>Back to flows</button><button data-add>Add scene</button><button data-export>Export</button>${this.draft.readonly ? '' : '<button data-reset>Reset from standard</button>'}<button data-play>Play flow</button><button data-save class="sr-primary">Save</button></div><table class="sr-scene-table"><thead><tr><th>On</th><th>#</th><th>Scene</th><th>Route</th><th>Talking points</th><th>Actions</th><th></th></tr></thead><tbody>${this.draft.scenes.map((scene, index) => `<tr draggable="true" data-index="${index}"><td><input type="checkbox" data-enabled ${scene.enabled !== false ? 'checked' : ''}></td><td>${index + 1}</td><td><strong>${esc(scene.title)}</strong></td><td class="sr-route">${esc(scene.route)}</td><td class="sr-notes-preview">${esc(scene.talkingPoints)}</td><td>${scene.actions.length}</td><td class="sr-row"><button data-up title="Move up">↑</button><button data-down title="Move down">↓</button><button data-edit>Edit</button><button data-remove class="sr-danger">Delete</button></td></tr>`).join('')}</tbody></table></section>`;
    this.body.querySelector('[data-back]').onclick = () => this.backToFlows(); this.body.querySelector('[data-save]').onclick = () => this.save(); this.body.querySelector('[data-export]').onclick = () => this.exportFlow(); this.body.querySelector('[data-play]').onclick = () => { if (!this.save()) return; this.close(); this.projector.enable(); this.projector.store.setPosition(0); this.projector.play(); };
    this.body.querySelector('[data-add]').onclick = () => { this.ensureEditable(); const scene = { id: window.ScreenReelStore.makeId('scene'), enabled: true, route: window.ScreenReelCore.normalizeRoute(this.projector.router.getRoute(), location.href) || '/', title: 'New scene', talkingPoints: '', dwellMs: 6000, actions: [] }; this.draft.scenes.push(scene); this.sceneId = scene.id; this.view = 'editor'; this.dirty = true; this.render(); };
    const reset = this.body.querySelector('[data-reset]'); if (reset) reset.onclick = () => { if (!confirm('Replace this flow’s scenes with the first canonical flow?')) return; const standard = clone(this.store.standardFlows[0]); this.draft.scenes = standard.scenes; this.draft.defaults = standard.defaults; this.dirty = true; this.render(); };
    this.body.querySelectorAll('tbody tr').forEach((row) => {
      const index = Number(row.dataset.index); row.querySelector('[data-enabled]').onchange = (e) => { this.ensureEditable(); this.draft.scenes[index].enabled = e.target.checked; this.dirty = true; };
      row.querySelector('[data-edit]').onclick = () => { this.sceneId = this.draft.scenes[index].id; this.view = 'editor'; this.render(); };
      row.querySelector('[data-remove]').onclick = () => { if (!confirm('Delete this scene from the local flow?')) return; this.ensureEditable(); this.draft.scenes.splice(index, 1); this.dirty = true; this.render(); };
      row.querySelector('[data-up]').onclick = () => this.moveScene(index, index - 1); row.querySelector('[data-down]').onclick = () => this.moveScene(index, index + 1);
      row.ondragstart = () => { this.dragIndex = index; row.classList.add('dragging'); }; row.ondragend = () => row.classList.remove('dragging'); row.ondragover = (e) => e.preventDefault(); row.ondrop = () => this.moveScene(this.dragIndex, index);
    });
  }
  moveScene(from, to) { if (to < 0 || to >= this.draft.scenes.length || from === to) return; this.ensureEditable(); const [scene] = this.draft.scenes.splice(from, 1); this.draft.scenes.splice(to, 0, scene); this.dirty = true; this.render(); }
  scene() { return this.draft?.scenes.find((scene) => scene.id === this.sceneId); }
  previewRoute(route) { const url = new URL(route, location.href); url.searchParams.set('screenreelPreview', '1'); return `${url.pathname}${url.search}${url.hash}`; }
  renderEditor() {
    const scene = this.scene(); if (!scene) { this.view = 'scenes'; return this.render(); }
    this.body.innerHTML = `<section class="sr-page"><div class="sr-toolbar"><button data-back>Back to scenes</button><button data-play-scene>Play scene</button><button data-add-action>Add action</button><button data-save class="sr-primary">Save</button></div><div class="sr-fields"><div class="sr-field"><label>Scene title</label><input data-field="title" value="${esc(scene.title)}"></div><div class="sr-field"><label>Route</label><input data-field="route" value="${esc(scene.route)}"></div><div class="sr-field"><label>Scene time (ms)</label><input type="number" min="100" max="120000" data-field="dwellMs" value="${Number(scene.dwellMs || 6000)}"></div><div class="sr-field wide"><label>Talking points</label><textarea data-field="talkingPoints">${esc(scene.talkingPoints)}</textarea></div></div><div class="sr-editor-grid"><section class="sr-preview-panel"><div class="sr-preview-tools"><strong>Product preview</strong><input readonly value="${esc(scene.route)}"><button data-reload>Reload</button></div><div class="sr-preview-frame-wrap"><div class="sr-picker-banner" hidden>Pick a target · ↑ parent · ↓ child · Esc cancel</div><iframe class="sr-preview-frame" src="${esc(this.previewRoute(scene.route))}" title="Scene preview"></iframe></div></section><aside class="sr-timeline"><div class="sr-timeline-head"><strong>Sequence</strong><span>${scene.actions.length} actions</span></div><div class="sr-actions">${scene.actions.length ? scene.actions.map((action, index) => this.actionRow(action, index)).join('') : '<div class="sr-empty">Add the first action to this scene.</div>'}</div></aside></div></section>`;
    this.frame = this.body.querySelector('.sr-preview-frame'); this.body.querySelector('[data-back]').onclick = () => { this.view = 'scenes'; this.render(); }; this.body.querySelector('[data-save]').onclick = () => this.save(); this.body.querySelector('[data-reload]').onclick = () => this.frame.contentWindow.location.reload(); this.body.querySelector('[data-add-action]').onclick = () => this.openCatalog(); this.body.querySelector('[data-play-scene]').onclick = () => this.playScene();
    this.body.querySelectorAll('[data-field]').forEach((input) => input.oninput = () => { this.ensureEditable(); const value = input.type === 'number' ? Number(input.value) : input.value; this.scene()[input.dataset.field] = value; this.dirty = true; });
    this.body.querySelectorAll('[data-action-index]').forEach((row) => { const index = Number(row.dataset.actionIndex); row.querySelector('[data-action-edit]').onclick = () => this.editAction(index); row.querySelector('[data-action-up]').onclick = () => this.moveAction(index, index - 1); row.querySelector('[data-action-down]').onclick = () => this.moveAction(index, index + 1); row.querySelector('[data-action-delete]').onclick = () => { this.ensureEditable(); this.scene().actions.splice(index, 1); this.dirty = true; this.render(); }; });
  }
  actionRow(action, index) { const definition = window.ScreenReelCore.definitionForAction(action); return `<article class="sr-action ${this.failedAction === index ? 'failed' : ''}" data-action-index="${index}"><span class="sr-action-index">${index + 1}</span><div><strong>${esc(definition?.label || action.type)}</strong><small>${esc(action.selector || action.url || action.fn || `${action.ms || ''} ms`)}</small></div><div><button data-action-up>↑</button><button data-action-down>↓</button><button data-action-edit>Edit</button><button data-action-delete>×</button></div></article>`; }
  moveAction(from, to) { if (to < 0 || to >= this.scene().actions.length) return; this.ensureEditable(); const [action] = this.scene().actions.splice(from, 1); this.scene().actions.splice(to, 0, action); this.dirty = true; this.render(); }
  openCatalog() {
    const categories = [...new Set(window.ScreenReelCore.definitions.map((item) => item.category))]; const modal = this.modal(`<h2>Add action</h2><div class="sr-field"><label>Search actions</label><input data-search placeholder="Highlight, click, wait…"></div><div class="sr-catalog">${categories.flatMap((category) => window.ScreenReelCore.definitions.filter((item) => item.category === category).map((item) => `<button data-definition="${item.id}"><strong>${esc(item.label)}</strong><span>${esc(category)} · ${esc(item.picker)}</span></button>`)).join('')}</div><h2>Recipes</h2><div class="sr-catalog">${window.ScreenReelCore.recipes.map((item) => `<button data-recipe="${item.id}"><strong>${esc(item.label)}</strong><span>Inserts editable primitive actions</span></button>`).join('')}</div>`);
    const filter = () => modal.querySelectorAll('.sr-catalog button').forEach((button) => button.hidden = !button.textContent.toLowerCase().includes(modal.querySelector('[data-search]').value.toLowerCase())); modal.querySelector('[data-search]').oninput = filter;
    modal.querySelectorAll('[data-definition]').forEach((button) => button.onclick = () => { const definition = window.ScreenReelCore.getDefinition(button.dataset.definition); modal.remove(); const action = { id: window.ScreenReelStore.makeId('action'), type: definition.type, definitionId: definition.id, ...clone(definition.defaults) }; definition.picker === 'none' ? this.addActions([action]) : this.startPicker(definition.picker, (selection) => this.addActions([{ ...action, ...selection }])); });
    modal.querySelectorAll('[data-recipe]').forEach((button) => button.onclick = () => { const recipe = window.ScreenReelCore.recipes.find((item) => item.id === button.dataset.recipe); modal.remove(); recipe.picker === 'none' ? this.addActions(recipe.build({})) : this.startPicker(recipe.picker, (selection) => this.addActions(recipe.build(selection))); });
  }
  addActions(actions) { this.ensureEditable(); this.scene().actions.push(...actions.map((action) => ({ id: window.ScreenReelStore.makeId('action'), ...action }))); this.dirty = true; this.render(); }
  startPicker(policy, done) {
    const frameDoc = this.frame?.contentDocument; if (!frameDoc) return this.toast('Preview is not available for picking'); const banner = this.body.querySelector('.sr-picker-banner'); banner.hidden = false; let phase = 0; let target = null; let previousChild = null; let sourceSelector = null;
    const outline = frameDoc.createElement('div'); outline.className = 'sr-selector-outline'; Object.assign(outline.style, { position: 'fixed', zIndex: '2147483640', pointerEvents: 'none', border: '3px solid #8b5cf6', borderRadius: '9px', boxShadow: '0 0 0 2px #fff,0 0 22px rgba(124,58,237,.55)' }); frameDoc.body.appendChild(outline); const place = (el) => { target = el; const rect = el.getBoundingClientRect(); Object.assign(outline.style, { left: `${rect.left - 4}px`, top: `${rect.top - 4}px`, width: `${rect.width + 8}px`, height: `${rect.height + 8}px` }); };
    const hover = (e) => { const resolved = window.ScreenReelCore.resolvePickerTarget(e.target, policy === 'source-destination' ? (phase ? 'visual' : 'interactive') : policy, frameDoc); if (resolved) place(resolved); };
    const click = (e) => { e.preventDefault(); e.stopPropagation(); if (!target) return; const selector = policy === 'collection' ? window.ScreenReelCore.selectorForCollection(target) : window.ScreenReelCore.selectorFor(target); if (policy === 'source-destination' && phase === 0) { sourceSelector = selector; phase = 1; banner.textContent = 'Now pick the destination · Esc cancels'; return; } cleanup(); done(policy === 'source-destination' ? { selector: sourceSelector, toSelector: selector } : { selector }); this.toast(`${target.tagName.toLowerCase()} selected · ${frameDoc.querySelectorAll(selector).length} match`); };
    const key = (e) => { if (e.key === 'Escape') cleanup(); else if (e.key === 'ArrowUp' && target?.parentElement && target.parentElement !== frameDoc.body) { previousChild = target; place(target.parentElement); } else if (e.key === 'ArrowDown' && previousChild) { place(previousChild); previousChild = null; } };
    const cleanup = () => { frameDoc.removeEventListener('mousemove', hover, true); frameDoc.removeEventListener('click', click, true); frameDoc.defaultView.removeEventListener('keydown', key, true); outline.remove(); banner.hidden = true; this.cancelPicker = () => {}; };
    frameDoc.addEventListener('mousemove', hover, true); frameDoc.addEventListener('click', click, true); frameDoc.defaultView.addEventListener('keydown', key, true); this.cancelPicker = cleanup;
  }
  cancelPicker() {}
  editAction(index) {
    const action = this.scene().actions[index]; if (action.locked) return this.toast('Unknown imported actions are preserved but locked'); const definition = window.ScreenReelCore.definitionForAction(action); if (!definition) return;
    const specs = [...(definition.picker !== 'none' ? [{ key: 'selector', label: 'Target selector', type: 'text' }] : []), ...(definition.fields || []), { key: 'afterMs', label: 'Delay after action (ms)', type: 'number', min: 0, max: 30000 }]; const modal = this.modal(`<h2>${esc(definition.label)}</h2><div class="sr-fields">${specs.map((spec) => this.fieldHtml(spec, action[spec.key])).join('')}</div><div class="sr-modal-actions"><button data-cancel>Cancel</button><button data-apply class="sr-primary">Apply</button></div>`);
    modal.querySelector('[data-cancel]').onclick = () => modal.remove(); modal.querySelector('[data-apply]').onclick = () => { this.ensureEditable(); specs.forEach((spec) => { const input = modal.querySelector(`[data-key="${spec.key}"]`); let value = spec.type === 'checkbox' ? input.checked : spec.type === 'number' ? Number(input.value) : input.value; if (spec.type === 'json') { try { value = JSON.parse(input.value); } catch { return; } } this.scene().actions[index][spec.key] = value; }); this.dirty = true; modal.remove(); this.render(); };
  }
  fieldHtml(spec, value) { if (spec.type === 'checkbox') return `<label class="sr-field"><span>${esc(spec.label)}</span><input data-key="${spec.key}" type="checkbox" ${value ? 'checked' : ''}></label>`; if (spec.type === 'select') return `<label class="sr-field"><span>${esc(spec.label)}</span><select data-key="${spec.key}">${spec.options.map((option) => `<option${option === value ? ' selected' : ''}>${esc(option)}</option>`).join('')}</select></label>`; if (spec.type === 'textarea' || spec.type === 'json') return `<label class="sr-field wide"><span>${esc(spec.label)}</span><textarea data-key="${spec.key}">${esc(spec.type === 'json' ? JSON.stringify(value ?? []) : value ?? '')}</textarea></label>`; return `<label class="sr-field"><span>${esc(spec.label)}</span><input data-key="${spec.key}" type="${spec.type === 'number' ? 'number' : 'text'}" value="${esc(value ?? '')}" ${spec.min != null ? `min="${spec.min}"` : ''} ${spec.max != null ? `max="${spec.max}"` : ''}></label>`; }
  modal(html) { const backdrop = document.createElement('div'); backdrop.className = 'sr-modal-backdrop'; backdrop.innerHTML = `<div class="sr-modal">${html}</div>`; this.shell.appendChild(backdrop); backdrop.onclick = (e) => { if (e.target === backdrop) backdrop.remove(); }; return backdrop; }
  async playScene() { const win = this.frame?.contentWindow; const doc = this.frame?.contentDocument; if (!doc) return this.toast('Preview is unavailable'); this.failedAction = -1; for (let index = 0; index < this.scene().actions.length; index++) { const result = await window.ScreenReelCore.runAction(this.scene().actions[index], { document: doc, window: win, navigate: (route) => { this.frame.src = this.previewRoute(route); } }); if (!result.ok) { this.failedAction = index; this.toast(`Action ${index + 1} failed`); this.render(); return; } if (result.navigated) return; } this.toast('Scene completed'); }
  save() {
    if (this.draft.readonly) { this.toast('Edit a scene first to create a local copy'); return false; }
    const errors = [];
    for (const scene of this.draft.scenes) {
      if (!window.ScreenReelCore.normalizeRoute(scene.route, location.href)) errors.push(`${scene.title}: invalid local route`);
      if (scene.dwellMs != null && (!Number.isFinite(Number(scene.dwellMs)) || Number(scene.dwellMs) < 100 || Number(scene.dwellMs) > 120000)) errors.push(`${scene.title}: invalid scene time`);
      if (scene.id === this.sceneId) for (const action of scene.actions) if (!action.locked) errors.push(...window.ScreenReelCore.validate(action, this.frame?.contentDocument, location.href).map((message) => `${scene.title}: ${message}`));
    }
    if (errors.length) { this.toast(errors[0]); return false; }
    this.draft = this.store.save(this.draft); this.flowId = this.draft.id; this.dirty = false; this.toast('Saved locally'); this.render(); return true;
  }
  exportFlow() { const blob = new Blob([JSON.stringify(this.store.export(this.draft), null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${this.draft.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.screenreel.json`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }
  importFile() { const input = document.createElement('input'); input.type = 'file'; input.accept = '.json,application/json'; input.onchange = async () => { try { const flow = this.store.import(JSON.parse(await input.files[0].text())); this.flowId = flow.id; this.view = 'scenes'; this.loadDraft(); this.render(); } catch (error) { this.toast(error.message); } }; input.click(); }
  async copyAiContext() { const scene = this.scene(); let targets = []; try { targets = this.frame?.contentDocument ? window.ScreenReelCore.inspectDocument(this.frame.contentDocument) : []; } catch {} const payload = { schemaVersion: 1, projectId: this.store.projectId, flow: this.draft ? { id: this.draft.id, name: this.draft.name } : null, scene: scene || null, stableTargets: targets, validation: scene ? scene.actions.map((action, index) => ({ index, actionId: action.id, errors: action.locked ? [] : window.ScreenReelCore.validate(action, this.frame?.contentDocument, location.href) })) : [] }; const text = JSON.stringify(payload, null, 2); try { await navigator.clipboard.writeText(text); } catch { const area = document.createElement('textarea'); area.value = text; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); } this.toast('AI context copied'); }
  backToFlows() { if (this.dirty && !confirm('Discard unsaved ScreenReel changes?')) return; this.view = 'flows'; this.flowId = null; this.sceneId = null; this.draft = null; this.dirty = false; this.render(); }
}

export function openStudio(options) { if (activeStudio) return activeStudio; activeStudio = new Studio(options).open(); return activeStudio; }
